# Generated by Django 4.1 on 2022-09-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_watchlistitem_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchlistItem',
            new_name='MyWatchList',
        ),
    ]
